<h2 style='color:blue' align="center">Decision Tree Classification</h2>

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("salaries.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [33]:
inputs = df.drop('salary_more_then_100k',axis='columns')

In [34]:
target = df['salary_more_then_100k']

In [35]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [36]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])

In [37]:
inputs

       company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [38]:
inputs_n = inputs.drop(['company','job','degree'],axis='columns')

In [39]:
inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [40]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [41]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [42]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [43]:
model.score(inputs_n,target)

1.0

**Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?**

In [44]:
model.predict([[2,1,0]])

/Users/M365491/development/ai/py/.venv/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

**Is salary of Google, Computer Engineer, Masters degree > 100 k ?**

In [45]:
model.predict([[2,1,1]])

/Users/M365491/development/ai/py/.venv/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

**Exercise: Build decision tree model to predict survival based on certain parameters**

<img src="titanic.jpg" height=200 width=400/>

CSV file is available to download at https://github.com/codebasics/py/blob/master/ML/9_decision_tree/Exercise/titanic.csv

##### In this file using following columns build a model to predict if person would survive or not,

1. Pclass
1. Sex
1. Age
1. Fare

##### Calculate score of your model

In [46]:
# load titanic data
import pandas as pd
dftitanic = pd.read_csv("./Exercise/titanic.csv")
dftitanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [47]:
dftitanic = dftitanic.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
dftitanic

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [48]:
dftitanic_inputs = dftitanic.drop('Survived',axis='columns')
dftitanic_target = dftitanic['Survived']

In [49]:
dftitanic_inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [50]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
# encode sex column with le_sex
dftitanic_inputs["sex_n"] = le_sex.fit_transform(dftitanic["Sex"])

In [52]:
dftitanic_inputs = dftitanic_inputs.drop('Sex', axis='columns', errors='ignore')
dftitanic_inputs

     Pclass   Age     Fare  sex_n
0         3  22.0   7.2500      1
1         1  38.0  71.2833      0
2         3  26.0   7.9250      0
3         1  35.0  53.1000      0
4         3  35.0   8.0500      1
..      ...   ...      ...    ...
886       2  27.0  13.0000      1
887       1  19.0  30.0000      0
888       3   NaN  23.4500      0
889       1  26.0  30.0000      1
890       3  32.0   7.7500      1

[891 rows x 4 columns]

In [55]:
# fill missing age values with mean
dftitanic_inputs.Age = dftitanic_inputs.Age.fillna(dftitanic_inputs.Age.mean())
dftitanic_inputs

     Pclass        Age     Fare  sex_n
0         3  22.000000   7.2500      1
1         1  38.000000  71.2833      0
2         3  26.000000   7.9250      0
3         1  35.000000  53.1000      0
4         3  35.000000   8.0500      1
..      ...        ...      ...    ...
886       2  27.000000  13.0000      1
887       1  19.000000  30.0000      0
888       3  29.699118  23.4500      0
889       1  26.000000  30.0000      1
890       3  32.000000   7.7500      1

[891 rows x 4 columns]

In [56]:
# generate x_train, x_test, y_train, y_test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dftitanic_inputs, dftitanic_target, test_size=0.2)

In [57]:
# create decision tree model
from sklearn import tree
model = tree.DecisionTreeClassifier()
# train model
model.fit(x_train, y_train)
# score model
model.score(x_test, y_test)

0.770949720670391